const S = [
  {a:"Live",o:"With Big Wreck & Econoline Crush",d:"MAR 2 · 2026",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"concert",e:"🎸",g:"#051a10,#0d0520",tags:[["tc","Concert"],["tr","Alt Rock"]],y:2026},
  {a:"WPW: Rumble at The Burt",o:"",d:"OCT 19 · 2025",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"wrestling",e:"🤼",g:"#1a0800,#0a0a0a",tags:[["to","Wrestling"],["ta","Local"]],y:2025,img:"professional wrestling"},
  {a:"Korn",o:"With Gojira & Loathe",d:"SEP 25 · 2025",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"concert",e:"🤘",g:"#1a0505,#0d1a0d",tags:[["tc","Concert"],["tr","Metal"]],y:2025},
  {a:"WPW: I Still Know Who You Pinned Last Summer",o:"",d:"JUL 18 · 2025",v:"BLUE NOTE PARK · WINNIPEG, MB",t:"wrestling",e:"🤼",g:"#1a0800,#0a0a0a",tags:[["to","Wrestling"],["ta","Outdoor"]],y:2025,img:"professional wrestling"},
  {a:"Bush",o:"With Shinedown",d:"APR 29 · 2025",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"concert",e:"🎸",g:"#0d1520,#1a0d05",tags:[["tc","Concert"],["ta","90s Rock"]],y:2025},
  {a:"WPW: Rumble at The Burt",o:"",d:"OCT 24 · 2024",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"wrestling",e:"🤼",g:"#1a0800,#0a0a0a",tags:[["to","Wrestling"],["ta","Local"]],y:2024,img:"professional wrestling"},
  {a:"Carrie Underwood",o:"",d:"AUG 16 · 2024",v:"RESORTS WORLD LAS VEGAS",t:"concert",e:"🌟",g:"#1a1005,#200520",tags:[["tc","Concert"],["ta","Las Vegas"]],y:2024},
  {a:"Mat Franco",o:"",d:"AUG 14 · 2024",v:"THE LINQ · LAS VEGAS, NV",t:"theatre",e:"🎩",g:"#05051a,#1a051a",tags:[["to","Magic"],["ta","Las Vegas"]],y:2024,img:"magician"},
  {a:"AEW: Dynamite & Rampage",o:"",d:"MAY 1 · 2024",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"wrestling",e:"🏆",g:"#1a0500,#00051a",tags:[["to","Wrestling"],["tb","AEW"]],y:2024,img:"All Elite Wrestling"},
  {a:"NHL: Colorado Avalanche vs Winnipeg Jets — Game 2",o:"",d:"APR 23 · 2024",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"sport",e:"🏒",g:"#001a10,#1a0020",tags:[["tb","NHL Playoffs"],["ta","Home"]],y:2024,img:"Winnipeg Jets"},
  {a:"Queens of the Stone Age",o:"With The Struts",d:"APR 5 · 2024",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"concert",e:"🔥",g:"#200505,#0d0520",tags:[["tc","Concert"],["tr","Rock"]],y:2024},
  {a:"Cirque du Soleil: Corteo",o:"",d:"DEC 8 · 2023",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"theatre",e:"🎪",g:"#05051a,#1a0505",tags:[["to","Cirque"],["tp","Theatre"]],y:2023,img:"Cirque du Soleil"},
  {a:"KISS",o:"With Crown Lands",d:"NOV 15 · 2023",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"concert",e:"💋",g:"#1a0a00,#0a0a1a",tags:[["tc","Concert"],["tr","Farewell Tour"]],y:2023},
  {a:"MLB: Detroit Tigers vs Minnesota Twins",o:"",d:"AUG 15 · 2023",v:"TARGET FIELD · MINNEAPOLIS, MN",t:"sport",e:"⚾",g:"#001a15,#1a1000",tags:[["tb","MLB"],["ta","Road Trip"]],y:2023,img:"baseball stadium"},
  {a:"Ed Sheeran",o:"With Khalid & Cat Burns",d:"AUG 12 · 2023",v:"US BANK STADIUM · MINNEAPOLIS, MN",t:"concert",e:"🎵",g:"#1a1000,#0d1a0d",tags:[["tc","Concert"],["ta","Stadium"]],y:2023},
  {a:"AEW: Forbidden Door",o:"",d:"JUN 25 · 2023",v:"SCOTIABANK ARENA · TORONTO, ON",t:"wrestling",e:"🚪",g:"#1a0500,#00051a",tags:[["to","Wrestling"],["tb","AEW PPV"],["ta","Road Trip"]],y:2023,img:"All Elite Wrestling"},
  {a:"MLB: Oakland Athletics vs Toronto Blue Jays",o:"",d:"JUN 25 · 2023",v:"ROGERS CENTRE · TORONTO, ON",t:"sport",e:"⚾",g:"#001a15,#1a1000",tags:[["tb","MLB"],["ta","Road Trip"]],y:2023,img:"Toronto Blue Jays"},
  {a:"NHL: Vegas Golden Knights vs Winnipeg Jets — Game 4",o:"",d:"APR 24 · 2023",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"sport",e:"🏒",g:"#001a10,#1a0a00",tags:[["tb","NHL Playoffs"],["ta","Home"]],y:2023,img:"Winnipeg Jets"},
  {a:"Rage Against the Machine",o:"With Run the Jewels",d:"MAR 16 · 2023",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"cancelled",e:"✊",g:"#200505,#050520",tags:[["tr","CANCELLED"]],y:2023},
  {a:"AEW: Dynamite & Rampage",o:"",d:"MAR 15 · 2023",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"wrestling",e:"🏆",g:"#1a0500,#00051a",tags:[["to","Wrestling"],["tb","AEW"]],y:2023,img:"All Elite Wrestling"},
  {a:"The Sheepdogs",o:"With Boy Golden",d:"NOV 22 · 2022",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"concert",e:"🐕",g:"#0d1505,#1a0d05",tags:[["tc","Concert"],["ta","Local Venue"]],y:2022},
  {a:"AEW: Rampage",o:"",d:"OCT 13 · 2022",v:"COCA COLA COLISEUM · TORONTO, ON",t:"wrestling",e:"🏆",g:"#1a0500,#00051a",tags:[["to","Wrestling"],["tb","AEW"],["ta","Road Trip"]],y:2022,img:"All Elite Wrestling"},
  {a:"AEW: Dynamite",o:"",d:"OCT 12 · 2022",v:"COCA COLA COLISEUM · TORONTO, ON",t:"wrestling",e:"🏆",g:"#1a0500,#00051a",tags:[["to","Wrestling"],["tb","AEW"],["ta","Road Trip"]],y:2022,img:"All Elite Wrestling"},
  {a:"Michael Bublé",o:"",d:"OCT 7 · 2022",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"concert",e:"🎷",g:"#050d1a,#1a1005",tags:[["tc","Concert"],["ta","Jazz/Pop"]],y:2022,img:"Michael Buble"},
  {a:"Foo Fighters",o:"",d:"SEP 21 · 2022",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"cancelled",e:"🥁",g:"#1a0505,#050a1a",tags:[["tr","CANCELLED"]],y:2022},
  {a:"Greta Van Fleet",o:"With The Pretty Reckless & Hannah Wicklund",d:"AUG 22 · 2022",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"concert",e:"🔥",g:"#1a0800,#0d0020",tags:[["tc","Concert"],["tr","Rock"]],y:2022},
  {a:"The Glorious Sons",o:"With JJ Wilde",d:"JUN 16 · 2022",v:"CANADA LIFE CENTRE · WINNIPEG, MB",t:"concert",e:"🎸",g:"#1a0505,#051a05",tags:[["tc","Concert"],["ta","Canadian Rock"]],y:2022},
  {a:"AEW: Double or Nothing",o:"",d:"MAY 29 · 2022",v:"T-MOBILE ARENA · LAS VEGAS, NV",t:"wrestling",e:"🏆",g:"#1a0500,#00051a",tags:[["to","Wrestling"],["tb","AEW PPV"],["ta","Las Vegas"]],y:2022,img:"All Elite Wrestling"},
  {a:"The Sheepdogs",o:"With Said the Whale",d:"AUG 21 · 2021",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"concert",e:"🐕",g:"#0d1505,#1a0d05",tags:[["tc","Concert"],["ta","Post-COVID"]],y:2021},
  {a:"Kidz Bop World Tour",o:"",d:"FEB 28 · 2020",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"kids",e:"🎤",g:"#1a0520,#051a15",tags:[["tk","Kids Show"]],y:2020,img:"Kidz Bop"},
  {a:"WWE: Monday Night Raw",o:"",d:"FEB 24 · 2020",v:"BELL MTS PLACE · WINNIPEG, MB",t:"wrestling",e:"🤼",g:"#1a0000,#0a0a1a",tags:[["to","Wrestling"],["tr","WWE"]],y:2020,img:"WWE wrestling"},
  {a:"KISS",o:"With David Lee Roth",d:"FEB 22 · 2020",v:"ALERUS CENTER · GRAND FORKS, ND",t:"concert",e:"💋",g:"#1a0a00,#0a0a1a",tags:[["tc","Concert"],["ta","Road Trip"]],y:2020},
  {a:"NHL: Heritage Classic — Calgary Flames vs Winnipeg Jets",o:"",d:"OCT 26 · 2019",v:"MOSAIC STADIUM · REGINA, SK",t:"sport",e:"🏒",g:"#001a10,#1a0505",tags:[["tb","NHL"],["tg","Heritage Classic"]],y:2019,img:"Winnipeg Jets"},
  {a:"Cirque du Soleil — Amaluna",o:"",d:"OCT 6 · 2019",v:"KENASTON & STERLING LYON FIELD · WINNIPEG, MB",t:"theatre",e:"🎪",g:"#05051a,#1a0505",tags:[["to","Cirque"],["tp","Theatre"]],y:2019,img:"Cirque du Soleil"},
  {a:"Elton John",o:"",d:"OCT 4 · 2019",v:"BELL MTS PLACE · WINNIPEG, MB",t:"concert",e:"🎹",g:"#1a1000,#1a0020",tags:[["tc","Concert"],["ta","Farewell Tour"]],y:2019},
  {a:"NFL: Oakland Raiders vs Green Bay Packers — Preseason",o:"",d:"AUG 22 · 2019",v:"IG FIELD · WINNIPEG, MB",t:"sport",e:"🏈",g:"#0a1500,#1a0500",tags:[["tb","NFL Preseason"],["tg","Home"]],y:2019,img:"NFL football"},
  {a:"Rob Zombie",o:"With Marilyn Manson",d:"AUG 7 · 2019",v:"BELL MTS PLACE · WINNIPEG, MB",t:"concert",e:"🧟",g:"#1a0000,#0a001a",tags:[["tc","Concert"],["tr","Metal"]],y:2019},
  {a:"MLB: Los Angeles Dodgers vs Boston Red Sox",o:"",d:"JUL 13 · 2019",v:"FENWAY PARK · BOSTON, MA",t:"sport",e:"⚾",g:"#1a0000,#001a05",tags:[["tb","MLB"],["tr","Bucket List"],["ta","Fenway"]],y:2019,img:"Fenway Park baseball"},
  {a:"WWE: House Show",o:"",d:"JUN 14 · 2019",v:"BELL MTS PLACE · WINNIPEG, MB",t:"wrestling",e:"🤼",g:"#1a0000,#0a0a1a",tags:[["to","Wrestling"],["tr","WWE"]],y:2019,img:"WWE wrestling"},
  {a:"Cher",o:"",d:"MAY 21 · 2019",v:"BELL MTS PLACE · WINNIPEG, MB",t:"cancelled",e:"💃",g:"#1a0020,#200010",tags:[["tr","CANCELLED"]],y:2019},
  {a:"The Tea Party",o:"With The Proud Sons",d:"APR 24 · 2019",v:"CLUB REGENT EVENT CENTRE · WINNIPEG, MB",t:"concert",e:"🍵",g:"#0d1505,#1a0505",tags:[["tc","Concert"],["ta","Canadian Rock"]],y:2019},
  {a:"Michael Bublé",o:"",d:"APR 19 · 2019",v:"BELL MTS PLACE · WINNIPEG, MB",t:"concert",e:"🎷",g:"#050d1a,#1a1005",tags:[["tc","Concert"]],y:2019,img:"Michael Buble"},
  {a:"NHL: St. Louis Blues vs Winnipeg Jets — Game 2",o:"",d:"APR 12 · 2019",v:"BELL MTS PLACE · WINNIPEG, MB",t:"sport",e:"🏒",g:"#001a10,#1a0020",tags:[["tb","NHL Playoffs"],["ta","Home"]],y:2019,img:"Winnipeg Jets"},
  {a:"Russell Peters",o:"",d:"NOV 13 · 2018",v:"BELL MTS PLACE · WINNIPEG, MB",t:"comedy",e:"🎤",g:"#1a1505,#051a15",tags:[["ty","Comedy"]],y:2018},
  {a:"Cirque du Soleil — Crystal",o:"",d:"OCT 6 · 2018",v:"BELL MTS PLACE · WINNIPEG, MB",t:"theatre",e:"❄️",g:"#05101a,#0a051a",tags:[["to","Cirque"],["tp","Theatre"]],y:2018,img:"Cirque du Soleil"},
  {a:"Paul McCartney",o:"",d:"SEP 28 · 2018",v:"BELL MTS PLACE · WINNIPEG, MB",t:"concert",e:"🎸",g:"#0d1a05,#1a0d1a",tags:[["tc","Concert"],["ta","Legend"]],y:2018},
  {a:"NFL: Buffalo Bills vs Minnesota Vikings",o:"",d:"SEP 23 · 2018",v:"US BANK STADIUM · MINNEAPOLIS, MN",t:"sport",e:"🏈",g:"#0a1500,#1a0500",tags:[["tb","NFL"],["ta","Road Trip"]],y:2018,img:"NFL football"},
  {a:"Metallica",o:"",d:"SEP 13 · 2018",v:"BELL MTS PLACE · WINNIPEG, MB",t:"concert",e:"⚡",g:"#1a1a00,#0a0a0a",tags:[["tc","Concert"],["tr","Metal"]],y:2018},
  {a:"Queens of the Stone Age",o:"Rescheduled — Couldn't Attend New Date",d:"MAY 20 · 2018",v:"RESCHEDULED",t:"cancelled",e:"🔥",g:"#200505,#0d0520",tags:[["tr","COULDN'T ATTEND"]],y:2018},
  {a:"NHL: Nashville Predators vs Winnipeg Jets — Game 6",o:"",d:"MAY 7 · 2018",v:"BELL MTS PLACE · WINNIPEG, MB",t:"sport",e:"🏒",g:"#001a10,#1a0a00",tags:[["tb","NHL Playoffs"],["ta","Home"]],y:2018,img:"Winnipeg Jets"},
  {a:"NHL: Minnesota Wild vs Winnipeg Jets — Game 2",o:"",d:"APR 13 · 2018",v:"BELL MTS PLACE · WINNIPEG, MB",t:"sport",e:"🏒",g:"#001a10,#1a0a00",tags:[["tb","NHL Playoffs"],["ta","Home"]],y:2018,img:"Winnipeg Jets"},
  {a:"2018 World Men's Curling Championships",o:"",d:"MAR 31 – APR 8 · 2018",v:"ORLEANS ARENA · LAS VEGAS, NV",t:"curling",e:"🥌",g:"#051a15,#1a0510",tags:[["tg","Curling"],["tb","World Championship"],["ta","Las Vegas"]],y:2018,img:"curling sport"},
  {a:"The Sheepdogs",o:"With Sam Coffey and the Iron Lungs",d:"FEB 24 · 2018",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"concert",e:"🐕",g:"#0d1505,#1a0d05",tags:[["tc","Concert"]],y:2018},
  {a:"Chris D'Elia",o:"",d:"FEB 10 · 2018",v:"CLUB REGENT EVENT CENTRE · WINNIPEG, MB",t:"comedy",e:"😂",g:"#1a1505,#051a15",tags:[["ty","Comedy"]],y:2018},
  {a:"NFL: New Orleans Saints vs Minnesota Vikings — Divisional Round",o:"",d:"JAN 14 · 2018",v:"US BANK STADIUM · MINNEAPOLIS, MN",t:"sport",e:"🏈",g:"#0a1500,#1a0500",tags:[["tb","NFL Playoffs"],["tr","Miracle"],["ta","Road Trip"]],y:2018,img:"NFL football"},
  {a:"NHL: Winnipeg Jets vs Minnesota Wild",o:"",d:"JAN 13 · 2018",v:"XCEL ENERGY CENTER · ST. PAUL, MN",t:"sport",e:"🏒",g:"#001a10,#1a0020",tags:[["tb","NHL"],["ta","Road Trip"]],y:2018,img:"Winnipeg Jets"},
  {a:"Demetri Martin",o:"",d:"NOV 17 · 2017",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"comedy",e:"✏️",g:"#1a1505,#051a15",tags:[["ty","Comedy"]],y:2017},
  {a:"Roger Waters",o:"",d:"OCT 23 · 2017",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🎩",g:"#05051a,#1a0505",tags:[["tc","Concert"],["tp","Pink Floyd"]],y:2017},
  {a:"NFL: New Orleans Saints vs Minnesota Vikings",o:"",d:"SEP 11 · 2017",v:"US BANK STADIUM · MINNEAPOLIS, MN",t:"sport",e:"🏈",g:"#0a1500,#1a0500",tags:[["tb","NFL"],["tg","Stadium Opener"],["ta","Road Trip"]],y:2017,img:"NFL football"},
  {a:"Guns N' Roses",o:"With Our Lady Peace",d:"AUG 24 · 2017",v:"INVESTORS GROUP FIELD · WINNIPEG, MB",t:"concert",e:"🌹",g:"#1a0800,#0d001a",tags:[["tc","Concert"],["tr","Rock"],["ta","Reunion"]],y:2017,img:"Guns N Roses"},
  {a:"The Offspring",o:"With Sublime with Rome",d:"JUL 12 · 2017",v:"RBC CONVENTION CENTRE · WINNIPEG, MB",t:"concert",e:"🤟",g:"#1a0505,#051510",tags:[["tc","Concert"],["tr","Punk Rock"]],y:2017},
  {a:"Kurios — Cirque du Soleil: Cabinet of Curiosities",o:"",d:"JUN 4 · 2017",v:"KENASTON & STERLING LYON FIELD · WINNIPEG, MB",t:"theatre",e:"⚙️",g:"#0d1015,#15100d",tags:[["to","Cirque"],["tp","Theatre"]],y:2017,img:"Cirque du Soleil"},
  {a:"Red Hot Chili Peppers",o:"With Trombone Shorty & Orleans Avenue",d:"MAY 26 · 2017",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🌶",g:"#1a0505,#050d20",tags:[["tc","Concert"],["tr","Rock"]],y:2017},
  {a:"Stomp",o:"",d:"MAY 6 · 2017",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"theatre",e:"🥁",g:"#0a0a0a,#1a0a05",tags:[["to","Theatre"],["tp","Performance"]],y:2017,img:"Stomp performance"},
  {a:"David Copperfield",o:"",d:"MAR 29 · 2017",v:"MGM GRAND · LAS VEGAS, NV",t:"theatre",e:"🎩",g:"#05051a,#1a051a",tags:[["to","Magic"],["ta","Las Vegas"]],y:2017},
  {a:"Jerry Seinfeld",o:"",d:"DEC 17 · 2016",v:"MTS CENTRE · WINNIPEG, MB",t:"comedy",e:"😄",g:"#1a1505,#051a15",tags:[["ty","Comedy"]],y:2016},
  {a:"Cirque Musica Holiday Spectacular",o:"",d:"NOV 30 · 2016",v:"MTS CENTRE · WINNIPEG, MB",t:"theatre",e:"🎄",g:"#051a05,#1a0505",tags:[["to","Cirque"],["tp","Theatre"]],y:2016,img:"Cirque du Soleil"},
  {a:"NHL: Heritage Classic — Edmonton Oilers vs Winnipeg Jets",o:"",d:"OCT 23 · 2016",v:"INVESTORS GROUP FIELD · WINNIPEG, MB",t:"sport",e:"🏒",g:"#001a10,#1a0800",tags:[["tb","NHL"],["tg","Heritage Classic"]],y:2016,img:"Winnipeg Jets"},
  {a:"Alice Cooper",o:"",d:"OCT 11 · 2016",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"concert",e:"🐍",g:"#0d0505,#1a0505",tags:[["tc","Concert"],["tr","Rock"]],y:2016},
  {a:"Cirque du Soleil: Toruk — The First Flight",o:"",d:"OCT 7 · 2016",v:"MTS CENTRE · WINNIPEG, MB",t:"theatre",e:"🐲",g:"#05101a,#0a1a05",tags:[["to","Cirque"],["ta","Avatar"]],y:2016,img:"Cirque du Soleil"},
  {a:"I Mother Earth",o:"With The Standstills",d:"OCT 6 · 2016",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"concert",e:"🌍",g:"#051a0a,#0d0520",tags:[["tc","Concert"],["ta","Canadian Rock"]],y:2016},
  {a:"Metallica",o:"With Avenged Sevenfold & Volbeat",d:"AUG 20 · 2016",v:"US BANK STADIUM · MINNEAPOLIS, MN",t:"concert",e:"⚡",g:"#1a1a00,#0a0a0a",tags:[["tc","Concert"],["tr","Metal"],["ta","Road Trip"]],y:2016},
  {a:"Chris Cornell",o:"With Fantastic Negrito",d:"JUL 27 · 2016",v:"CENTENNIAL CONCERT HALL · WINNIPEG, MB",t:"concert",e:"🖤",g:"#0a0a0a,#1a0505",tags:[["tc","Concert"],["ta","Intimate"]],y:2016},
  {a:"WWE: House Show",o:"",d:"MAY 28 · 2016",v:"MTS CENTRE · WINNIPEG, MB",t:"wrestling",e:"🤼",g:"#1a0000,#0a0a1a",tags:[["to","Wrestling"],["tr","WWE"]],y:2016,img:"WWE wrestling"},
  {a:"The Who",o:"With Slydigs",d:"MAY 4 · 2016",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🔊",g:"#050d1a,#1a0505",tags:[["tc","Concert"],["ta","Legend"]],y:2016},
  {a:"Death From Above 1979",o:"With Eagles of Death Metal",d:"MAY 1 · 2016",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"concert",e:"💀",g:"#1a0505,#051a1a",tags:[["tc","Concert"],["tr","Punk"]],y:2016},
  {a:"Kevin Nealon & Norm MacDonald",o:"",d:"APR 15 · 2016",v:"CLUB REGENT EVENT CENTRE · WINNIPEG, MB",t:"comedy",e:"😂",g:"#1a1505,#051a15",tags:[["ty","Comedy"],["ta","Double Bill"]],y:2016},
  {a:"The Sheepdogs",o:"With Beat Cops",d:"FEB 29 · 2016",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"concert",e:"🐕",g:"#0d1505,#1a0d05",tags:[["tc","Concert"],["ta","Leap Day!"]],y:2016},
  {a:"Darcy Oake",o:"",d:"DEC 4 · 2015",v:"MTS CENTRE · WINNIPEG, MB",t:"theatre",e:"🎩",g:"#05051a,#1a051a",tags:[["to","Magic"],["ta","Canadian"]],y:2015},
  {a:"The Price is Right: Live",o:"",d:"OCT 17 · 2015",v:"CLUB REGENT EVENT CENTRE · WINNIPEG, MB",t:"theatre",e:"💰",g:"#1a1000,#051a10",tags:[["to","Live Show"],["ty","Game Show"]],y:2015,img:"The Price is Right"},
  {a:"Slipknot",o:"With Suicidal Tendencies",d:"OCT 14 · 2015",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🎭",g:"#1a0505,#0a0a0a",tags:[["tc","Concert"],["tr","Metal"]],y:2015},
  {a:"Bubble Guppies Live!",o:"",d:"OCT 10 · 2015",v:"CENTENNIAL CONCERT HALL · WINNIPEG, MB",t:"kids",e:"🐟",g:"#051a15,#05051a",tags:[["tk","Kids Show"]],y:2015,img:"Bubble Guppies"},
  {a:"AC/DC",o:"With Vintage Trouble",d:"SEP 17 · 2015",v:"IG FIELD · WINNIPEG, MB",t:"concert",e:"⚡",g:"#1a0000,#0a0a0a",tags:[["tc","Concert"],["ta","Stadium"],["tr","Rock"]],y:2015},
  {a:"Chris D'Elia",o:"",d:"JUL 26 · 2015",v:"CLUB REGENT EVENT CENTRE · WINNIPEG, MB",t:"comedy",e:"😂",g:"#1a1505,#051a15",tags:[["ty","Comedy"]],y:2015},
  {a:"Cirque du Soleil: Varekai",o:"",d:"JUN 24 · 2015",v:"MTS CENTRE · WINNIPEG, MB",t:"theatre",e:"🎪",g:"#05051a,#1a0505",tags:[["to","Cirque"],["tp","Theatre"]],y:2015,img:"Cirque du Soleil"},
  {a:"NHL: Anaheim Ducks vs Winnipeg Jets — Game 3",o:"",d:"APR 20 · 2015",v:"MTS CENTRE · WINNIPEG, MB",t:"sport",e:"🏒",g:"#001a10,#1a0520",tags:[["tb","NHL Playoffs"],["ta","Home"]],y:2015,img:"Winnipeg Jets"},
  {a:"2015 Men's World Junior Championship",o:"",d:"DEC 31 – JAN 5 · 2014/15",v:"AIR CANADA CENTRE · TORONTO, ON",t:"sport",e:"🏒",g:"#001a10,#051a15",tags:[["tb","World Juniors"],["ta","Road Trip"]],y:2014,img:"hockey arena"},
  {a:"Norm MacDonald",o:"",d:"NOV 7 · 2014",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"comedy",e:"😐",g:"#1a1505,#051a15",tags:[["ty","Comedy"]],y:2014},
  {a:"Godsmack",o:"With Seether",d:"OCT 1 · 2014",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🔥",g:"#1a0505,#0d1505",tags:[["tc","Concert"],["tr","Metal"]],y:2014},
  {a:"Jersey Boys",o:"",d:"SEP 2 · 2014",v:"LE THEATRE DES ARTS · LAS VEGAS, NV",t:"theatre",e:"🎵",g:"#1a1000,#051a05",tags:[["to","Musical"],["ta","Las Vegas"]],y:2014,img:"Jersey Boys musical"},
  {a:"Tom Petty",o:"With Steve Winwood",d:"AUG 21 · 2014",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🌻",g:"#1a1000,#0d1a05",tags:[["tc","Concert"],["ta","Legend"]],y:2014},
  {a:"Michael Bublé",o:"With Naturally 7",d:"JUN 26 · 2014",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🎷",g:"#050d1a,#1a1005",tags:[["tc","Concert"]],y:2014,img:"Michael Buble"},
  {a:"WWE: House Show",o:"",d:"MAR 7 · 2014",v:"MTS CENTRE · WINNIPEG, MB",t:"wrestling",e:"🤼",g:"#1a0000,#0a0a1a",tags:[["to","Wrestling"],["tr","WWE"]],y:2014,img:"WWE wrestling"},
  {a:"Black Sabbath",o:"With Reignwolf",d:"APR 16 · 2014",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🖤",g:"#0a0a0a,#1a0505",tags:[["tc","Concert"],["tr","Metal"],["ta","Legend"]],y:2014},
  {a:"Cirque du Soleil: Love",o:"",d:"NOV 1 · 2013",v:"LOVE THEATRE · LAS VEGAS, NV",t:"theatre",e:"💗",g:"#1a051a,#1a1000",tags:[["to","Cirque"],["ta","Beatles Las Vegas"]],y:2013,img:"Cirque du Soleil Love"},
  {a:"Paul McCartney",o:"",d:"AUG 12 · 2013",v:"IG FIELD · WINNIPEG, MB",t:"concert",e:"🎸",g:"#0d1a05,#1a0d1a",tags:[["tc","Concert"],["ta","Stadium Legend"]],y:2013},
  {a:"MLB: Atlanta Braves vs Chicago White Sox",o:"",d:"JUL 20 · 2013",v:"U.S. CELLULAR FIELD · CHICAGO, IL",t:"sport",e:"⚾",g:"#001a05,#1a0000",tags:[["tb","MLB"],["ta","Road Trip"]],y:2013,img:"baseball stadium"},
  {a:"Pearl Jam",o:"",d:"JUL 19 · 2013",v:"WRIGLEY FIELD · CHICAGO, IL",t:"concert",e:"🌊",g:"#051a10,#050d1a",tags:[["tc","Concert"],["ta","Wrigley Field"],["tr","Grunge"]],y:2013},
  {a:"Marilyn Manson",o:"With Butcher Babies",d:"FEB 4 · 2013",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🎭",g:"#1a0505,#050520",tags:[["tc","Concert"],["tr","Shock Rock"]],y:2013},
  {a:"Bob Dylan",o:"With Mark Knopfler",d:"OCT 5 · 2012",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🎤",g:"#0d1505,#1a0d05",tags:[["tc","Concert"],["ta","Legend"]],y:2012},
  {a:"Buddy Guy",o:"With Jonny Lang",d:"SEP 21 · 2012",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🎸",g:"#1a0a00,#0a0510",tags:[["tc","Concert"],["ta","Blues"]],y:2012},
  {a:"Slash with Myles Kennedy",o:"With Monster Truck",d:"JUL 21 · 2012",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"concert",e:"🎩",g:"#0a0a0a,#1a0505",tags:[["tc","Concert"],["ta","Intimate"]],y:2012,img:"Slash guitarist"},
  {a:"Roger Waters",o:"",d:"JUN 1 · 2012",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🎩",g:"#05051a,#1a0505",tags:[["tc","Concert"],["tp","The Wall"]],y:2012},
  {a:"Rammstein",o:"With Joe Letz",d:"MAY 10 · 2012",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🔥",g:"#1a0505,#0a0a0a",tags:[["tc","Concert"],["tr","Industrial Metal"]],y:2012},
  {a:"Pearl Jam",o:"With Mudhoney",d:"SEP 19 · 2011",v:"CREDIT UNION CENTRE · SASKATOON, SK",t:"concert",e:"🌊",g:"#051a10,#050d1a",tags:[["tc","Concert"],["ta","Road Trip"]],y:2011},
  {a:"U2",o:"With The Fray",d:"MAY 29 · 2011",v:"WINNIPEG STADIUM · WINNIPEG, MB",t:"concert",e:"🏟",g:"#050d1a,#1a0505",tags:[["tc","Concert"],["ta","Stadium"],["tp","360 Tour"]],y:2011},
  {a:"WWE: Raw World Tour",o:"",d:"MAY 27 · 2011",v:"MTS CENTRE · WINNIPEG, MB",t:"wrestling",e:"🤼",g:"#1a0000,#0a0a1a",tags:[["to","Wrestling"],["tr","WWE"]],y:2011,img:"WWE wrestling"},
  {a:"WWE: Supershow",o:"",d:"OCT 23 · 2010",v:"MTS CENTRE · WINNIPEG, MB",t:"wrestling",e:"🤼",g:"#1a0000,#0a0a1a",tags:[["to","Wrestling"],["tr","WWE"]],y:2010,img:"WWE wrestling"},
  {a:"NFL: Dallas Cowboys vs Minnesota Vikings",o:"",d:"OCT 17 · 2010",v:"MALL OF AMERICA FIELD · MINNEAPOLIS, MN",t:"sport",e:"🏈",g:"#0a1500,#1a0500",tags:[["tb","NFL"],["ta","Road Trip"]],y:2010,img:"NFL football"},
  {a:"NHL: Columbus Blue Jackets vs Minnesota Wild",o:"",d:"OCT 16 · 2010",v:"XCEL ENERGY CENTER · ST. PAUL, MN",t:"sport",e:"🏒",g:"#001a10,#1a0020",tags:[["tb","NHL"],["ta","Road Trip"]],y:2010,img:"NHL hockey"},
  {a:"Black Label Society",o:"With Children of Bodom, Clutch & 2Cents",d:"SEP 28 · 2010",v:"WINNIPEG CONVENTION CENTRE · WINNIPEG, MB",t:"concert",e:"⚡",g:"#0a0a0a,#1a0505",tags:[["tc","Concert"],["tr","Metal"]],y:2010},
  {a:"Slash with Myles Kennedy",o:"",d:"SEP 24 · 2010",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"concert",e:"🎩",g:"#0a0a0a,#1a0505",tags:[["tc","Concert"],["ta","Intimate"]],y:2010,img:"Slash guitarist"},
  {a:"Tool",o:"With dälek",d:"JUL 4 · 2010",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🔧",g:"#050a1a,#0a0a0a",tags:[["tc","Concert"],["tr","Progressive Metal"]],y:2010},
  {a:"Korn",o:"With Five Finger Death Punch",d:"APR 3 · 2010",v:"WINNIPEG CONVENTION CENTRE · WINNIPEG, MB",t:"concert",e:"🤘",g:"#1a0505,#0d1a0d",tags:[["tc","Concert"],["tr","Nu-Metal"]],y:2010},
  {a:"NBA: Detroit Pistons vs Toronto Raptors",o:"",d:"DEC 27 · 2009",v:"AIR CANADA CENTRE · TORONTO, ON",t:"sport",e:"🏀",g:"#1a0500,#001a10",tags:[["tb","NBA"],["ta","Road Trip"]],y:2009,img:"NBA basketball"},
  {a:"NHL: Montreal Canadiens vs Toronto Maple Leafs",o:"",d:"DEC 26 · 2009",v:"AIR CANADA CENTRE · TORONTO, ON",t:"sport",e:"🏒",g:"#001a00,#1a0505",tags:[["tb","NHL"],["tr","Classic Rivalry"],["ta","Road Trip"]],y:2009,img:"NHL hockey"},
  {a:"Stone Temple Pilots",o:"",d:"NOV 15 · 2009",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🪨",g:"#0d1505,#1a0d05",tags:[["tc","Concert"],["tr","Grunge"]],y:2009},
  {a:"KISS",o:"With Buckcherry",d:"NOV 9 · 2009",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"💋",g:"#1a0a00,#0a0a1a",tags:[["tc","Concert"],["ta","Glam Rock"]],y:2009},
  {a:"Metallica",o:"With Lamb of God & Gojira",d:"OCT 12 · 2009",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"⚡",g:"#1a1a00,#0a0a0a",tags:[["tc","Concert"],["tr","Metal"]],y:2009},
  {a:"AC/DC",o:"With The Answer",d:"AUG 22 · 2009",v:"WINNIPEG STADIUM · WINNIPEG, MB",t:"concert",e:"⚡",g:"#1a0000,#0a0a0a",tags:[["tc","Concert"],["ta","Stadium"]],y:2009},
  {a:"No Fear Energy Tour",o:"Lamb of God, As I Lay Dying, Children of Bodom, God Forbid, Municipal Waste",d:"APR 13 · 2009",v:"WINNIPEG CONVENTION CENTRE · WINNIPEG, MB",t:"concert",e:"🤘",g:"#1a0505,#051a05",tags:[["tc","Concert"],["tr","Metal Festival"]],y:2009,img:"Lamb of God"},
  {a:"NFL: Green Bay Packers vs Minnesota Vikings",o:"",d:"NOV 9 · 2008",v:"H.H.H. METRODOME · MINNEAPOLIS, MN",t:"sport",e:"🏈",g:"#0a1500,#1a0500",tags:[["tb","NFL"],["ta","Road Trip"]],y:2008,img:"NFL football"},
  {a:"Tom Petty",o:"With Steve Winwood",d:"AUG 9 · 2008",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🌻",g:"#1a1000,#0d1a05",tags:[["tc","Concert"],["ta","Legend"]],y:2008},
  {a:"Slayer",o:"",d:"JUL 30 · 2008",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"⚔️",g:"#1a0000,#0a000a",tags:[["tc","Concert"],["tr","Thrash Metal"]],y:2008},
  {a:"Megadeth",o:"With In Flames, Children of Bodom, Job for a Cowboy & High on Fire",d:"MAY 10 · 2008",v:"WINNIPEG CONVENTION CENTRE · WINNIPEG, MB",t:"concert",e:"💀",g:"#1a0a00,#0a0a0a",tags:[["tc","Concert"],["tr","Thrash Metal"]],y:2008},
  {a:"Foo Fighters",o:"With Against Me!",d:"MAR 25 · 2008",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🥁",g:"#1a0505,#050a1a",tags:[["tc","Concert"],["tr","Rock"]],y:2008},
  {a:"Collective Soul",o:"",d:"FEB 9 · 2008",v:"BURTON CUMMINGS THEATRE · WINNIPEG, MB",t:"concert",e:"🎸",g:"#050d1a,#1a051a",tags:[["tc","Concert"],["ta","Intimate"]],y:2008},
  {a:"Velvet Revolver",o:"With Sparta",d:"OCT 14 · 2007",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🔫",g:"#1a0505,#0d0520",tags:[["tc","Concert"],["tr","Rock Supergroup"]],y:2007},
  {a:"Queens of the Stone Age",o:"With Cage the Elephant",d:"AUG 26 · 2007",v:"WINNIPEG CONVENTION CENTRE · WINNIPEG, MB",t:"concert",e:"🔥",g:"#200505,#0d0520",tags:[["tc","Concert"],["tr","Rock"]],y:2007},
  {a:"Rise Against",o:"With Silverstein, Comeback Kid & Holy Roman Empire",d:"JUL 16 · 2007",v:"WINNIPEG CONVENTION CENTRE · WINNIPEG, MB",t:"concert",e:"✊",g:"#1a0505,#051a05",tags:[["tc","Concert"],["tr","Punk Rock"]],y:2007},
  {a:"Weird Al",o:"",d:"JUN 20 · 2007",v:"MTS CENTRE · WINNIPEG, MB",t:"comedy",e:"🪗",g:"#1a1505,#051a15",tags:[["ty","Comedy"],["ta","Parody"]],y:2007},
  {a:"Sam Roberts",o:"",d:"NOV 17 · 2006",v:"WINNIPEG CONVENTION CENTRE · WINNIPEG, MB",t:"concert",e:"🎸",g:"#0d1505,#1a0d05",tags:[["tc","Concert"],["ta","Canadian"]],y:2006},
  {a:"NFL: Carolina Panthers vs Minnesota Vikings",o:"",d:"SEP 17 · 2006",v:"H.H.H. METRODOME · MINNEAPOLIS, MN",t:"sport",e:"🏈",g:"#0a1500,#1a0500",tags:[["tb","NFL"],["ta","Road Trip"]],y:2006,img:"NFL football"},
  {a:"Black Eyed Peas",o:"",d:"SEP 30 · 2006",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🎤",g:"#1a0d1a,#050d1a",tags:[["tc","Concert"],["tp","Pop/Hip-Hop"]],y:2006},
  {a:"Sounds of the Underground 2006",o:"GWAR, As I Lay Dying, In Flames, Trivium, Cannibal Corpse, Terror, The Black Dahlia Murder, Behemoth, The Chariot, Through the Eyes of the Dead",d:"AUG 6 · 2006",v:"WINNIPEG CONVENTION CENTRE · WINNIPEG, MB",t:"concert",e:"💀",g:"#1a0505,#05051a",tags:[["tc","Concert"],["tr","Metal Festival"]],y:2006,img:"GWAR"},
  {a:"Godsmack",o:"With X Engine X",d:"JUN 17 · 2006",v:"WINNIPEG CONVENTION CENTRE · WINNIPEG, MB",t:"concert",e:"🔥",g:"#1a0505,#0d1505",tags:[["tc","Concert"],["tr","Metal"]],y:2006},
  {a:"Aerosmith",o:"With Lenny Kravitz",d:"DEC 8 · 2005",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🚀",g:"#1a0a00,#051a15",tags:[["tc","Concert"],["tr","Rock"],["ta","Legend"]],y:2005},
  {a:"Nine Inch Nails",o:"With Queens of the Stone Age",d:"NOV 14 · 2005",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🔩",g:"#0a0a0a,#1a0505",tags:[["tc","Concert"],["tr","Industrial"]],y:2005},
  {a:"Audioslave",o:"With Thirty Seconds to Mars & Seether",d:"OCT 4 · 2005",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🎸",g:"#0d0510,#1a0505",tags:[["tc","Concert"],["tr","Rock"]],y:2005},
  {a:"NFL: Tampa Bay Buccaneers vs Minnesota Vikings",o:"",d:"SEP 11 · 2005",v:"H.H.H. METRODOME · MINNEAPOLIS, MN",t:"sport",e:"🏈",g:"#0a1500,#1a0500",tags:[["tb","NFL"],["ta","Road Trip"]],y:2005,img:"NFL football"},
  {a:"Pearl Jam",o:"With Supersuckers",d:"SEP 8 · 2005",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🌊",g:"#051a10,#050d1a",tags:[["tc","Concert"],["tr","Grunge"]],y:2005},
  {a:"Foo Fighters",o:"With Sloan & Constantines",d:"AUG 10 · 2005",v:"MTS CENTRE · WINNIPEG, MB",t:"concert",e:"🥁",g:"#1a0505,#050a1a",tags:[["tc","Concert"],["tr","Rock"]],y:2005},
  {a:"Velvet Revolver",o:"",d:"MAR 27 · 2005",v:"CREDIT UNION CENTRE · SASKATOON, SK",t:"concert",e:"🔫",g:"#1a0505,#0d0520",tags:[["tc","Concert"],["ta","Road Trip"]],y:2005},
  {a:"NFL: Jacksonville Jaguars vs Minnesota Vikings",o:"",d:"NOV 28 · 2004",v:"H.H.H. METRODOME · MINNEAPOLIS, MN",t:"sport",e:"🏈",g:"#0a1500,#1a0500",tags:[["tb","NFL"],["ta","Road Trip"]],y:2004,img:"NFL football"},
  {a:"WWF: Monday Night Raw",o:"",d:"JUL 5 · 2004",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"wrestling",e:"🤼",g:"#1a0000,#0a0a1a",tags:[["to","Wrestling"],["tr","WWE"]],y:2004,img:"WWE wrestling"},
  {a:"Aerosmith",o:"With Cheap Trick",d:"MAY 14 · 2004",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"concert",e:"🚀",g:"#1a0a00,#051a15",tags:[["tc","Concert"],["ta","Legend"]],y:2004},
  {a:"NFL: Detroit Lions vs Minnesota Vikings",o:"",d:"NOV 23 · 2003",v:"H.H.H. METRODOME · MINNEAPOLIS, MN",t:"sport",e:"🏈",g:"#0a1500,#1a0500",tags:[["tb","NFL"],["ta","Road Trip"]],y:2003,img:"NFL football"},
  {a:"Aerosmith",o:"With KISS",d:"NOV 8 · 2003",v:"ALERUS CENTRE · GRAND FORKS, ND",t:"concert",e:"🚀",g:"#1a0a00,#0a001a",tags:[["tc","Concert"],["ta","Road Trip"],["tr","Double Headliner"]],y:2003},
  {a:"NHL: New York Rangers vs Tampa Bay Lightning",o:"",d:"DEC 29 · 2002",v:"ST. PETE TIMES FORUM · TAMPA, FL",t:"sport",e:"🏒",g:"#001a10,#051a15",tags:[["tb","NHL"],["tg","Sun Trip"],["ta","Road Trip"]],y:2002,img:"NHL hockey"},
  {a:"Nickelback",o:"With Default",d:"JAN 29 · 2002",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"concert",e:"🎸",g:"#0d1505,#1a0d05",tags:[["tc","Concert"],["ta","Canadian Rock"]],y:2002},
  {a:"NFL: New York Giants vs Minnesota Vikings",o:"",d:"NOV 21 · 2001",v:"H.H.H. METRODOME · MINNEAPOLIS, MN",t:"sport",e:"🏈",g:"#0a1500,#1a0500",tags:[["tb","NFL"],["ta","Road Trip"]],y:2001,img:"NFL football"},
  {a:"Summer Sault",o:"Our Lady Peace, Finger Eleven, A Perfect Circle, Foo Fighters, Smashing Pumpkins, Sum 41, Catherine Wheel, Eve 6, Treble Charger, I Mother Earth",d:"AUG 9 · 2000",v:"WINNIPEG STADIUM · WINNIPEG, MB",t:"festival",e:"☀️",g:"#1a1000,#051a10",tags:[["tp","Festival"],["ta","Stadium"],["tr","Legendary"]],y:2000,img:"Foo Fighters"},
  {a:"Korn",o:"With Papa Roach & Powerman 5000",d:"JUL 24 · 2000",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"concert",e:"🤘",g:"#1a0505,#0d1a0d",tags:[["tc","Concert"],["tr","Nu-Metal"]],y:2000},
  {a:"KISS",o:"With Ted Nugent",d:"JUL 16 · 2000",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"concert",e:"💋",g:"#1a0a00,#0a0a1a",tags:[["tc","Concert"],["ta","Pyro"]],y:2000},
  {a:"ECW on TNN",o:"",d:"MAY 6 · 2000",v:"SPORTS PAVILION · MINNEAPOLIS, MN",t:"wrestling",e:"📺",g:"#1a0000,#0a0510",tags:[["to","Wrestling"],["tr","ECW"]],y:2000,img:"ECW wrestling"},
  {a:"Nickelback",o:"With X Engine X",d:"FEB 10 · 2000",v:"THE ZOO (BAR) · WINNIPEG, MB",t:"concert",e:"🎸",g:"#0d1505,#1a0d05",tags:[["tc","Concert"],["ta","Club Show"]],y:2000},
  {a:"The Tea Party",o:"With Edwin",d:"NOV 19 · 1999",v:"WINNIPEG CONVENTION CENTRE · WINNIPEG, MB",t:"concert",e:"🍵",g:"#0d1505,#1a0505",tags:[["tc","Concert"],["ta","Canadian Rock"]],y:1999},
  {a:"WWF: SummerSlam 1999",o:"",d:"AUG 22 · 1999",v:"TARGET CENTER · MINNEAPOLIS, MN",t:"wrestling",e:"🤼",g:"#1a0000,#0a0a1a",tags:[["to","Wrestling"],["tr","WWF PPV"],["ta","Road Trip"]],y:1999,img:"WWE wrestling"},
  {a:"WCW: Monday Nitro",o:"",d:"APR 26 · 1999",v:"FARGODOME · FARGO, ND",t:"wrestling",e:"🔥",g:"#1a0000,#0a050a",tags:[["to","Wrestling"],["tr","WCW"],["ta","Road Trip"]],y:1999,img:"WCW wrestling"},
  {a:"WCW: Thunder",o:"",d:"AUG 20 · 1998",v:"FARGODOME · FARGO, ND",t:"wrestling",e:"⚡",g:"#1a0000,#0a050a",tags:[["to","Wrestling"],["tr","WCW"],["ta","Road Trip"]],y:1998,img:"WCW wrestling"},
  {a:"Classic Rock Weekend",o:"Alice Cooper, Randy Bachman, Pat Benatar, REO Speedwagon, Loverboy, Streetheart, Foreigner, April Wine, Toronto, Harlequin, Trooper, Burton Cummings",d:"AUG LONG · 1998",v:"MINNEDOSA, MB",t:"festival",e:"🎸",g:"#1a0800,#051a05",tags:[["tp","Festival"],["ta","Outdoor"]],y:1998,img:"Alice Cooper"},
  {a:"EdgeFest",o:"Creed, The Tea Party, Foo Fighters, Green Day, The Watchmen, Econoline Crush, Bif Naked, Sloan, Matthew Good Band, The Killjoys",d:"JUL 4 · 1998",v:"WINNIPEG STADIUM · WINNIPEG, MB",t:"festival",e:"⚡",g:"#050d1a,#1a0505",tags:[["tp","Festival"],["ta","Stadium"]],y:1998,img:"Foo Fighters"},
  {a:"EdgeFest",o:"Silverchair, Our Lady Peace, Finger Eleven, Collective Soul, The Tea Party, I Mother Earth, Econoline Crush, Philosopher Kings, Age of Electric, Sara Craig, Glueleg, Holly McNarland, The Verve Pipe, Dodgy",d:"SEP 1 · 1997",v:"WINNIPEG STADIUM · WINNIPEG, MB",t:"festival",e:"⚡",g:"#050d1a,#1a0505",tags:[["tp","Festival"],["ta","Stadium"]],y:1997,img:"Silverchair"},
  {a:"Bush",o:"With Veruca Salt",d:"JUN 25 · 1997",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"concert",e:"🌿",g:"#0d1520,#1a0d05",tags:[["tc","Concert"],["ta","90s Rock"]],y:1997},
  {a:"U2",o:"With Fun Lovin' Criminals",d:"JUN 12 · 1997",v:"WINNIPEG STADIUM · WINNIPEG, MB",t:"concert",e:"🏟",g:"#050d1a,#1a0505",tags:[["tc","Concert"],["ta","Stadium"],["tp","PopMart Tour"]],y:1997},
  {a:"KISS",o:"With Econoline Crush",d:"APR 30 · 1997",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"concert",e:"💋",g:"#1a0a00,#0a0a1a",tags:[["tc","Concert"],["ta","Reunion"]],y:1997},
  {a:"Our Lady Peace",o:"With Chantal Kreviazuk",d:"MAR 7 · 1997",v:"UNIVERSITY OF MANITOBA · WINNIPEG, MB",t:"concert",e:"☮️",g:"#051a15,#0d0520",tags:[["tc","Concert"],["ta","Campus Show"]],y:1997},
  {a:"Metallica",o:"With Corrosion of Conformity",d:"FEB 14 · 1997",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"concert",e:"⚡",g:"#1a1a00,#0a0a0a",tags:[["tc","Concert"],["tr","Metal"]],y:1997},
  {a:"Smashing Pumpkins",o:"With Grant Lee Buffalo",d:"SEP 24 · 1996",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"concert",e:"🎃",g:"#1a0505,#050d1a",tags:[["tc","Concert"],["tr","Alternative"]],y:1996},
  {a:"AC/DC",o:"",d:"AUG 6 · 1996",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"concert",e:"⚡",g:"#1a0000,#0a0a0a",tags:[["tc","Concert"],["ta","Legend"]],y:1996},
  {a:"Scorpions",o:"With Alice Cooper",d:"JUL 11 · 1996",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"concert",e:"🦂",g:"#1a0505,#05051a",tags:[["tc","Concert"],["tr","Rock"],["ta","Double Bill"]],y:1996},
  {a:"Ozzy Osbourne",o:"With Filter",d:"JUN 11 · 1996",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"concert",e:"🦇",g:"#0a0a0a,#1a0505",tags:[["tc","Concert"],["tr","Metal"],["ta","Legend"]],y:1996},
  {a:"NHL: Detroit Red Wings vs Winnipeg Jets — Game 3",o:"",d:"APR 21 · 1996",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"sport",e:"🏒",g:"#001a10,#1a0505",tags:[["tb","NHL Playoffs"],["ta","Home"],["tr","Last Jets Season"]],y:1996,img:"Winnipeg Jets"},
  {a:"Green Day",o:"With The Riverdales",d:"OCT 23 · 1995",v:"WINNIPEG ARENA · WINNIPEG, MB",t:"concert",e:"🟢",g:"#051a05,#0d0a1a",tags:[["tc","Concert"],["tr","Punk"],["ta","Dookie Era"]],y:1995}
];